# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auction.proto',
  package='com.cyberpointllc.stac.auction',
  syntax='proto2',
  serialized_pb=_b('\n\rauction.proto\x12\x1e\x63om.cyberpointllc.stac.auction\"\xb8\x04\n\nAuctionMsg\x12\x11\n\tauctionId\x18\x01 \x02(\t\x12=\n\x04type\x18\x02 \x02(\x0e\x32/.com.cyberpointllc.stac.auction.AuctionMsg.Type\x12\x44\n\ncommitment\x18\x03 \x01(\x0b\x32\x30.com.cyberpointllc.stac.auction.BidCommitmentMsg\x12\x44\n\ncomparison\x18\x04 \x01(\x0b\x32\x30.com.cyberpointllc.stac.auction.BidComparisonMsg\x12>\n\x05start\x18\x05 \x01(\x0b\x32/.com.cyberpointllc.stac.auction.AuctionStartMsg\x12<\n\x06reveal\x18\x06 \x01(\x0b\x32,.com.cyberpointllc.stac.auction.RevealBidMsg\x12:\n\x03\x65nd\x18\x07 \x01(\x0b\x32-.com.cyberpointllc.stac.auction.AuctionEndMsg\"\x91\x01\n\x04Type\x12\x11\n\rAUCTION_START\x10\x01\x12\x12\n\x0e\x42ID_COMMITMENT\x10\x02\x12\x0f\n\x0b\x42ID_RECEIPT\x10\x03\x12\x12\n\x0e\x42ID_COMPARISON\x10\x04\x12\x10\n\x0c\x42IDDING_OVER\x10\x05\x12\r\n\tCLAIM_WIN\x10\x06\x12\x0b\n\x07\x43ONCEDE\x10\x07\x12\x0f\n\x0b\x41UCTION_END\x10\x08\"n\n\x10\x42idCommitmentMsg\x12\x0c\n\x04hash\x18\x01 \x02(\x0c\x12\n\n\x02r1\x18\x02 \x02(\x01\x12@\n\tsharedVal\x18\x03 \x02(\x0b\x32-.com.cyberpointllc.stac.auction.BigIntegerMsg\"\xad\x01\n\x10\x42idComparisonMsg\x12=\n\x06values\x18\x01 \x03(\x0b\x32-.com.cyberpointllc.stac.auction.BigIntegerMsg\x12<\n\x05prime\x18\x02 \x02(\x0b\x32-.com.cyberpointllc.stac.auction.BigIntegerMsg\x12\x1c\n\x14needReturnComparison\x18\x03 \x02(\x08\"*\n\x0f\x41uctionStartMsg\x12\x17\n\x0fitemDescription\x18\x01 \x01(\t\"3\n\rAuctionEndMsg\x12\x0e\n\x06winner\x18\x01 \x02(\t\x12\x12\n\nwinningBid\x18\x02 \x02(\x05\"m\n\x0cRevealBidMsg\x12\n\n\x02r1\x18\x01 \x02(\x01\x12\n\n\x02r2\x18\x02 \x02(\x01\x12\x38\n\x01x\x18\x03 \x02(\x0b\x32-.com.cyberpointllc.stac.auction.BigIntegerMsg\x12\x0b\n\x03\x62id\x18\x04 \x02(\x05\"\x1e\n\rBigIntegerMsg\x12\r\n\x05value\x18\x01 \x02(\x0c\x42/\n\x1e\x63om.cyberpointllc.stac.auctionB\rAuctionProtos')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_AUCTIONMSG_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='com.cyberpointllc.stac.auction.AuctionMsg.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='AUCTION_START', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BID_COMMITMENT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BID_RECEIPT', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BID_COMPARISON', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BIDDING_OVER', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLAIM_WIN', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONCEDE', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUCTION_END', index=7, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=473,
  serialized_end=618,
)
_sym_db.RegisterEnumDescriptor(_AUCTIONMSG_TYPE)


_AUCTIONMSG = _descriptor.Descriptor(
  name='AuctionMsg',
  full_name='com.cyberpointllc.stac.auction.AuctionMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auctionId', full_name='com.cyberpointllc.stac.auction.AuctionMsg.auctionId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.cyberpointllc.stac.auction.AuctionMsg.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commitment', full_name='com.cyberpointllc.stac.auction.AuctionMsg.commitment', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comparison', full_name='com.cyberpointllc.stac.auction.AuctionMsg.comparison', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start', full_name='com.cyberpointllc.stac.auction.AuctionMsg.start', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reveal', full_name='com.cyberpointllc.stac.auction.AuctionMsg.reveal', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end', full_name='com.cyberpointllc.stac.auction.AuctionMsg.end', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AUCTIONMSG_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=618,
)


_BIDCOMMITMENTMSG = _descriptor.Descriptor(
  name='BidCommitmentMsg',
  full_name='com.cyberpointllc.stac.auction.BidCommitmentMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash', full_name='com.cyberpointllc.stac.auction.BidCommitmentMsg.hash', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r1', full_name='com.cyberpointllc.stac.auction.BidCommitmentMsg.r1', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sharedVal', full_name='com.cyberpointllc.stac.auction.BidCommitmentMsg.sharedVal', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=730,
)


_BIDCOMPARISONMSG = _descriptor.Descriptor(
  name='BidComparisonMsg',
  full_name='com.cyberpointllc.stac.auction.BidComparisonMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='com.cyberpointllc.stac.auction.BidComparisonMsg.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prime', full_name='com.cyberpointllc.stac.auction.BidComparisonMsg.prime', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='needReturnComparison', full_name='com.cyberpointllc.stac.auction.BidComparisonMsg.needReturnComparison', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=733,
  serialized_end=906,
)


_AUCTIONSTARTMSG = _descriptor.Descriptor(
  name='AuctionStartMsg',
  full_name='com.cyberpointllc.stac.auction.AuctionStartMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemDescription', full_name='com.cyberpointllc.stac.auction.AuctionStartMsg.itemDescription', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=908,
  serialized_end=950,
)


_AUCTIONENDMSG = _descriptor.Descriptor(
  name='AuctionEndMsg',
  full_name='com.cyberpointllc.stac.auction.AuctionEndMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='winner', full_name='com.cyberpointllc.stac.auction.AuctionEndMsg.winner', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='winningBid', full_name='com.cyberpointllc.stac.auction.AuctionEndMsg.winningBid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=952,
  serialized_end=1003,
)


_REVEALBIDMSG = _descriptor.Descriptor(
  name='RevealBidMsg',
  full_name='com.cyberpointllc.stac.auction.RevealBidMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='r1', full_name='com.cyberpointllc.stac.auction.RevealBidMsg.r1', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r2', full_name='com.cyberpointllc.stac.auction.RevealBidMsg.r2', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='com.cyberpointllc.stac.auction.RevealBidMsg.x', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bid', full_name='com.cyberpointllc.stac.auction.RevealBidMsg.bid', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1005,
  serialized_end=1114,
)


_BIGINTEGERMSG = _descriptor.Descriptor(
  name='BigIntegerMsg',
  full_name='com.cyberpointllc.stac.auction.BigIntegerMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='com.cyberpointllc.stac.auction.BigIntegerMsg.value', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1116,
  serialized_end=1146,
)

_AUCTIONMSG.fields_by_name['type'].enum_type = _AUCTIONMSG_TYPE
_AUCTIONMSG.fields_by_name['commitment'].message_type = _BIDCOMMITMENTMSG
_AUCTIONMSG.fields_by_name['comparison'].message_type = _BIDCOMPARISONMSG
_AUCTIONMSG.fields_by_name['start'].message_type = _AUCTIONSTARTMSG
_AUCTIONMSG.fields_by_name['reveal'].message_type = _REVEALBIDMSG
_AUCTIONMSG.fields_by_name['end'].message_type = _AUCTIONENDMSG
_AUCTIONMSG_TYPE.containing_type = _AUCTIONMSG
_BIDCOMMITMENTMSG.fields_by_name['sharedVal'].message_type = _BIGINTEGERMSG
_BIDCOMPARISONMSG.fields_by_name['values'].message_type = _BIGINTEGERMSG
_BIDCOMPARISONMSG.fields_by_name['prime'].message_type = _BIGINTEGERMSG
_REVEALBIDMSG.fields_by_name['x'].message_type = _BIGINTEGERMSG
DESCRIPTOR.message_types_by_name['AuctionMsg'] = _AUCTIONMSG
DESCRIPTOR.message_types_by_name['BidCommitmentMsg'] = _BIDCOMMITMENTMSG
DESCRIPTOR.message_types_by_name['BidComparisonMsg'] = _BIDCOMPARISONMSG
DESCRIPTOR.message_types_by_name['AuctionStartMsg'] = _AUCTIONSTARTMSG
DESCRIPTOR.message_types_by_name['AuctionEndMsg'] = _AUCTIONENDMSG
DESCRIPTOR.message_types_by_name['RevealBidMsg'] = _REVEALBIDMSG
DESCRIPTOR.message_types_by_name['BigIntegerMsg'] = _BIGINTEGERMSG

AuctionMsg = _reflection.GeneratedProtocolMessageType('AuctionMsg', (_message.Message,), dict(
  DESCRIPTOR = _AUCTIONMSG,
  __module__ = 'auction_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.auction.AuctionMsg)
  ))
_sym_db.RegisterMessage(AuctionMsg)

BidCommitmentMsg = _reflection.GeneratedProtocolMessageType('BidCommitmentMsg', (_message.Message,), dict(
  DESCRIPTOR = _BIDCOMMITMENTMSG,
  __module__ = 'auction_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.auction.BidCommitmentMsg)
  ))
_sym_db.RegisterMessage(BidCommitmentMsg)

BidComparisonMsg = _reflection.GeneratedProtocolMessageType('BidComparisonMsg', (_message.Message,), dict(
  DESCRIPTOR = _BIDCOMPARISONMSG,
  __module__ = 'auction_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.auction.BidComparisonMsg)
  ))
_sym_db.RegisterMessage(BidComparisonMsg)

AuctionStartMsg = _reflection.GeneratedProtocolMessageType('AuctionStartMsg', (_message.Message,), dict(
  DESCRIPTOR = _AUCTIONSTARTMSG,
  __module__ = 'auction_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.auction.AuctionStartMsg)
  ))
_sym_db.RegisterMessage(AuctionStartMsg)

AuctionEndMsg = _reflection.GeneratedProtocolMessageType('AuctionEndMsg', (_message.Message,), dict(
  DESCRIPTOR = _AUCTIONENDMSG,
  __module__ = 'auction_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.auction.AuctionEndMsg)
  ))
_sym_db.RegisterMessage(AuctionEndMsg)

RevealBidMsg = _reflection.GeneratedProtocolMessageType('RevealBidMsg', (_message.Message,), dict(
  DESCRIPTOR = _REVEALBIDMSG,
  __module__ = 'auction_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.auction.RevealBidMsg)
  ))
_sym_db.RegisterMessage(RevealBidMsg)

BigIntegerMsg = _reflection.GeneratedProtocolMessageType('BigIntegerMsg', (_message.Message,), dict(
  DESCRIPTOR = _BIGINTEGERMSG,
  __module__ = 'auction_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.auction.BigIntegerMsg)
  ))
_sym_db.RegisterMessage(BigIntegerMsg)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.cyberpointllc.stac.auctionB\rAuctionProtos'))
# @@protoc_insertion_point(module_scope)
