import sys

import processpackets


def location_from_pcap(pcap, hostname, port):
    '''
    returns a tuple of (request size, response size) that
    corresponds to the location request and response.
    If it cannot determine the location request/response pair,
    this will return the tuple (None, None).
    It is assumed that packets returned are generated by calling
    the steps in interact.py.
    '''
    transactions = processpackets.get_transactions(pcap, hostname, port)

    if len(transactions) > 7:
        request = transactions[6].get_req_size()
        response = transactions[7].get_resp_size()
        return request, response

    return None, None


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print "location.py <pcapfile> <hostname> <port>"
        sys.exit(-1)
    pcap = processpackets.read_pcap(sys.argv[1])
    print location_from_pcap(pcap, sys.argv[2], int(sys.argv[3]))
