# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: powerbrokermsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='powerbrokermsg.proto',
  package='com.cyberpointllc.stac.powerbroker',
  syntax='proto2',
  serialized_pb=_b('\n\x14powerbrokermsg.proto\x12\"com.cyberpointllc.stac.powerbroker\"\xaf\x03\n\x0b\x42\x61seMessage\x12\x42\n\x04type\x18\x01 \x02(\x0e\x32\x34.com.cyberpointllc.stac.powerbroker.BaseMessage.Type\x12S\n\x0f\x61uctionAnnounce\x18\x02 \x03(\x0b\x32:.com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage\x12M\n\x0c\x61uctionBegin\x18\x03 \x01(\x0b\x32\x37.com.cyberpointllc.stac.powerbroker.AuctionBeginMessage\x12\x13\n\x0b\x61uctionData\x18\x04 \x01(\x0c\"\xa2\x01\n\x04Type\x12\x14\n\x10\x43ONNECTION_START\x10\x01\x12\x14\n\x10\x41UCTION_ANNOUNCE\x10\x02\x12\x11\n\rAUCTION_BEGIN\x10\x03\x12\x14\n\x10\x42IDDING_FINISHED\x10\x04\x12\x10\n\x0c\x41UCTION_DATA\x10\x05\x12\x0f\n\x0b\x41UCTION_END\x10\x06\x12\x0f\n\x0bRESULTS_END\x10\x07\x12\x11\n\rPROCESS_START\x10\x08\"9\n\x16\x41uctionAnnounceMessage\x12\x13\n\x0bpowerAmount\x18\x01 \x02(\r\x12\n\n\x02id\x18\x02 \x02(\t\"=\n\x13\x41uctionBeginMessage\x12\x11\n\tauctionId\x18\x01 \x02(\t\x12\x13\n\x0bpowerAmount\x18\x02 \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_BASEMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='com.cyberpointllc.stac.powerbroker.BaseMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONNECTION_START', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUCTION_ANNOUNCE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUCTION_BEGIN', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BIDDING_FINISHED', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUCTION_DATA', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUCTION_END', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESULTS_END', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROCESS_START', index=7, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=330,
  serialized_end=492,
)
_sym_db.RegisterEnumDescriptor(_BASEMESSAGE_TYPE)


_BASEMESSAGE = _descriptor.Descriptor(
  name='BaseMessage',
  full_name='com.cyberpointllc.stac.powerbroker.BaseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='com.cyberpointllc.stac.powerbroker.BaseMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auctionAnnounce', full_name='com.cyberpointllc.stac.powerbroker.BaseMessage.auctionAnnounce', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auctionBegin', full_name='com.cyberpointllc.stac.powerbroker.BaseMessage.auctionBegin', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auctionData', full_name='com.cyberpointllc.stac.powerbroker.BaseMessage.auctionData', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BASEMESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=492,
)


_AUCTIONANNOUNCEMESSAGE = _descriptor.Descriptor(
  name='AuctionAnnounceMessage',
  full_name='com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='powerAmount', full_name='com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage.powerAmount', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage.id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=551,
)


_AUCTIONBEGINMESSAGE = _descriptor.Descriptor(
  name='AuctionBeginMessage',
  full_name='com.cyberpointllc.stac.powerbroker.AuctionBeginMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auctionId', full_name='com.cyberpointllc.stac.powerbroker.AuctionBeginMessage.auctionId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='powerAmount', full_name='com.cyberpointllc.stac.powerbroker.AuctionBeginMessage.powerAmount', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=614,
)

_BASEMESSAGE.fields_by_name['type'].enum_type = _BASEMESSAGE_TYPE
_BASEMESSAGE.fields_by_name['auctionAnnounce'].message_type = _AUCTIONANNOUNCEMESSAGE
_BASEMESSAGE.fields_by_name['auctionBegin'].message_type = _AUCTIONBEGINMESSAGE
_BASEMESSAGE_TYPE.containing_type = _BASEMESSAGE
DESCRIPTOR.message_types_by_name['BaseMessage'] = _BASEMESSAGE
DESCRIPTOR.message_types_by_name['AuctionAnnounceMessage'] = _AUCTIONANNOUNCEMESSAGE
DESCRIPTOR.message_types_by_name['AuctionBeginMessage'] = _AUCTIONBEGINMESSAGE

BaseMessage = _reflection.GeneratedProtocolMessageType('BaseMessage', (_message.Message,), dict(
  DESCRIPTOR = _BASEMESSAGE,
  __module__ = 'powerbrokermsg_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.powerbroker.BaseMessage)
  ))
_sym_db.RegisterMessage(BaseMessage)

AuctionAnnounceMessage = _reflection.GeneratedProtocolMessageType('AuctionAnnounceMessage', (_message.Message,), dict(
  DESCRIPTOR = _AUCTIONANNOUNCEMESSAGE,
  __module__ = 'powerbrokermsg_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage)
  ))
_sym_db.RegisterMessage(AuctionAnnounceMessage)

AuctionBeginMessage = _reflection.GeneratedProtocolMessageType('AuctionBeginMessage', (_message.Message,), dict(
  DESCRIPTOR = _AUCTIONBEGINMESSAGE,
  __module__ = 'powerbrokermsg_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.powerbroker.AuctionBeginMessage)
  ))
_sym_db.RegisterMessage(AuctionBeginMessage)


# @@protoc_insertion_point(module_scope)
