# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import comms_pb2 as comms__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='com.cyberpointllc.stac.withmi',
  syntax='proto2',
  serialized_pb=_b('\n\nchat.proto\x12\x1d\x63om.cyberpointllc.stac.withmi\x1a\x0b\x63omms.proto\"\xab\x03\n\tWithMiMsg\x12;\n\x04type\x18\x01 \x02(\x0e\x32-.com.cyberpointllc.stac.withmi.WithMiMsg.Type\x12\x0e\n\x06\x63hatId\x18\x02 \x02(\t\x12\x0c\n\x04user\x18\x03 \x02(\t\x12\x11\n\tmessageId\x18\x04 \x02(\x02\x12\x37\n\x07textMsg\x18\x05 \x01(\x0b\x32&.com.cyberpointllc.stac.withmi.ChatMsg\x12\x37\n\x07\x66ileMsg\x18\x06 \x01(\x0b\x32&.com.cyberpointllc.stac.withmi.FileMsg\x12=\n\nreceiptMsg\x18\x07 \x01(\x0b\x32).com.cyberpointllc.stac.withmi.ReceiptMsg\x12\x41\n\x0c\x63hatStateMsg\x18\x08 \x01(\x0b\x32+.com.cyberpointllc.stac.withmi.ChatStateMsg\"<\n\x04Type\x12\x08\n\x04\x43HAT\x10\x01\x12\x08\n\x04\x46ILE\x10\x02\x12\x10\n\x0cREAD_RECEIPT\x10\x03\x12\x0e\n\nCHAT_STATE\x10\x04\"\x1a\n\x07\x43hatMsg\x12\x0f\n\x07textMsg\x18\x02 \x02(\t\"\x8b\x01\n\x07\x46ileMsg\x12\x10\n\x08\x66ileName\x18\x01 \x02(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\x0c\x12\x11\n\ttotalSize\x18\x03 \x02(\r\x12\x15\n\rcurrentOffset\x18\x04 \x02(\r\x12\x1e\n\x0fzlibCompression\x18\x05 \x01(\x08:\x05\x66\x61lse\x12\x13\n\x04\x64one\x18\x06 \x01(\x08:\x05\x66\x61lse\"5\n\nReceiptMsg\x12\x16\n\x0e\x61\x63kedMessageId\x18\x01 \x02(\x02\x12\x0f\n\x07success\x18\x02 \x02(\x08\"H\n\x0c\x43hatStateMsg\x12\x38\n\x08publicId\x18\x01 \x03(\x0b\x32&.com.cyberpointllc.stac.comms.Identity')
  ,
  dependencies=[comms__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_WITHMIMSG_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='com.cyberpointllc.stac.withmi.WithMiMsg.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHAT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READ_RECEIPT', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAT_STATE', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=426,
  serialized_end=486,
)
_sym_db.RegisterEnumDescriptor(_WITHMIMSG_TYPE)


_WITHMIMSG = _descriptor.Descriptor(
  name='WithMiMsg',
  full_name='com.cyberpointllc.stac.withmi.WithMiMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='com.cyberpointllc.stac.withmi.WithMiMsg.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chatId', full_name='com.cyberpointllc.stac.withmi.WithMiMsg.chatId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='com.cyberpointllc.stac.withmi.WithMiMsg.user', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messageId', full_name='com.cyberpointllc.stac.withmi.WithMiMsg.messageId', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='textMsg', full_name='com.cyberpointllc.stac.withmi.WithMiMsg.textMsg', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fileMsg', full_name='com.cyberpointllc.stac.withmi.WithMiMsg.fileMsg', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='receiptMsg', full_name='com.cyberpointllc.stac.withmi.WithMiMsg.receiptMsg', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chatStateMsg', full_name='com.cyberpointllc.stac.withmi.WithMiMsg.chatStateMsg', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WITHMIMSG_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=486,
)


_CHATMSG = _descriptor.Descriptor(
  name='ChatMsg',
  full_name='com.cyberpointllc.stac.withmi.ChatMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='textMsg', full_name='com.cyberpointllc.stac.withmi.ChatMsg.textMsg', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=488,
  serialized_end=514,
)


_FILEMSG = _descriptor.Descriptor(
  name='FileMsg',
  full_name='com.cyberpointllc.stac.withmi.FileMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileName', full_name='com.cyberpointllc.stac.withmi.FileMsg.fileName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='com.cyberpointllc.stac.withmi.FileMsg.content', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='totalSize', full_name='com.cyberpointllc.stac.withmi.FileMsg.totalSize', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currentOffset', full_name='com.cyberpointllc.stac.withmi.FileMsg.currentOffset', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zlibCompression', full_name='com.cyberpointllc.stac.withmi.FileMsg.zlibCompression', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='done', full_name='com.cyberpointllc.stac.withmi.FileMsg.done', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=656,
)


_RECEIPTMSG = _descriptor.Descriptor(
  name='ReceiptMsg',
  full_name='com.cyberpointllc.stac.withmi.ReceiptMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ackedMessageId', full_name='com.cyberpointllc.stac.withmi.ReceiptMsg.ackedMessageId', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='com.cyberpointllc.stac.withmi.ReceiptMsg.success', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=658,
  serialized_end=711,
)


_CHATSTATEMSG = _descriptor.Descriptor(
  name='ChatStateMsg',
  full_name='com.cyberpointllc.stac.withmi.ChatStateMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='publicId', full_name='com.cyberpointllc.stac.withmi.ChatStateMsg.publicId', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=713,
  serialized_end=785,
)

_WITHMIMSG.fields_by_name['type'].enum_type = _WITHMIMSG_TYPE
_WITHMIMSG.fields_by_name['textMsg'].message_type = _CHATMSG
_WITHMIMSG.fields_by_name['fileMsg'].message_type = _FILEMSG
_WITHMIMSG.fields_by_name['receiptMsg'].message_type = _RECEIPTMSG
_WITHMIMSG.fields_by_name['chatStateMsg'].message_type = _CHATSTATEMSG
_WITHMIMSG_TYPE.containing_type = _WITHMIMSG
_CHATSTATEMSG.fields_by_name['publicId'].message_type = comms__pb2._IDENTITY
DESCRIPTOR.message_types_by_name['WithMiMsg'] = _WITHMIMSG
DESCRIPTOR.message_types_by_name['ChatMsg'] = _CHATMSG
DESCRIPTOR.message_types_by_name['FileMsg'] = _FILEMSG
DESCRIPTOR.message_types_by_name['ReceiptMsg'] = _RECEIPTMSG
DESCRIPTOR.message_types_by_name['ChatStateMsg'] = _CHATSTATEMSG

WithMiMsg = _reflection.GeneratedProtocolMessageType('WithMiMsg', (_message.Message,), dict(
  DESCRIPTOR = _WITHMIMSG,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.withmi.WithMiMsg)
  ))
_sym_db.RegisterMessage(WithMiMsg)

ChatMsg = _reflection.GeneratedProtocolMessageType('ChatMsg', (_message.Message,), dict(
  DESCRIPTOR = _CHATMSG,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.withmi.ChatMsg)
  ))
_sym_db.RegisterMessage(ChatMsg)

FileMsg = _reflection.GeneratedProtocolMessageType('FileMsg', (_message.Message,), dict(
  DESCRIPTOR = _FILEMSG,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.withmi.FileMsg)
  ))
_sym_db.RegisterMessage(FileMsg)

ReceiptMsg = _reflection.GeneratedProtocolMessageType('ReceiptMsg', (_message.Message,), dict(
  DESCRIPTOR = _RECEIPTMSG,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.withmi.ReceiptMsg)
  ))
_sym_db.RegisterMessage(ReceiptMsg)

ChatStateMsg = _reflection.GeneratedProtocolMessageType('ChatStateMsg', (_message.Message,), dict(
  DESCRIPTOR = _CHATSTATEMSG,
  __module__ = 'chat_pb2'
  # @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.withmi.ChatStateMsg)
  ))
_sym_db.RegisterMessage(ChatStateMsg)


# @@protoc_insertion_point(module_scope)
