// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: powerbrokermsg.proto

package net.roboticapex.broker;

import com.google.protobuf.AbstractMessage;

public final class Powerbrokermsg {
  private Powerbrokermsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BaseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cyberpointllc.stac.powerbroker.BaseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.cyberpointllc.stac.powerbroker.BaseMessage.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .com.cyberpointllc.stac.powerbroker.BaseMessage.Type type = 1;</code>
     */
    Powerbrokermsg.BaseMessage.Type getType();

    /**
     * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
     *
     * <pre>
     * we announce all of the auctions we're holding at the same time
     * </pre>
     */
    java.util.List<Powerbrokermsg.AuctionAnnounceMessage>
        getAuctionAnnounceList();
    /**
     * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
     *
     * <pre>
     * we announce all of the auctions we're holding at the same time
     * </pre>
     */
    Powerbrokermsg.AuctionAnnounceMessage getAuctionAnnounce(int index);
    /**
     * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
     *
     * <pre>
     * we announce all of the auctions we're holding at the same time
     * </pre>
     */
    int getAuctionAnnounceCount();
    /**
     * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
     *
     * <pre>
     * we announce all of the auctions we're holding at the same time
     * </pre>
     */
    java.util.List<? extends Powerbrokermsg.AuctionAnnounceMessageOrBuilder>
        getAuctionAnnounceOrBuilderList();
    /**
     * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
     *
     * <pre>
     * we announce all of the auctions we're holding at the same time
     * </pre>
     */
    Powerbrokermsg.AuctionAnnounceMessageOrBuilder getAuctionAnnounceOrBuilder(
        int index);

    /**
     * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
     *
     * <pre>
     * you're only allowed to start one auction at a time
     * </pre>
     */
    boolean hasAuctionBegin();
    /**
     * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
     *
     * <pre>
     * you're only allowed to start one auction at a time
     * </pre>
     */
    Powerbrokermsg.AuctionBeginMessage getAuctionBegin();
    /**
     * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
     *
     * <pre>
     * you're only allowed to start one auction at a time
     * </pre>
     */
    Powerbrokermsg.AuctionBeginMessageOrBuilder getAuctionBeginOrBuilder();

    /**
     * <code>optional bytes auctionData = 4;</code>
     *
     * <pre>
     * the bytes for auction api messageds
     * </pre>
     */
    boolean hasAuctionData();
    /**
     * <code>optional bytes auctionData = 4;</code>
     *
     * <pre>
     * the bytes for auction api messageds
     * </pre>
     */
    com.google.protobuf.ByteString getAuctionData();
  }
  /**
   * Protobuf type {@code com.cyberpointllc.stac.powerbroker.BaseMessage}
   */
  public  static final class BaseMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.cyberpointllc.stac.powerbroker.BaseMessage)
      BaseMessageOrBuilder {
    // Use BaseMessage.newBuilder() to construct.
    private BaseMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private BaseMessage() {
      type_ = 1;
      auctionAnnounce_ = java.util.Collections.emptyList();
      auctionData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              Powerbrokermsg.BaseMessage.Type value = Powerbrokermsg.BaseMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                auctionAnnounce_ = new java.util.ArrayList<Powerbrokermsg.AuctionAnnounceMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              auctionAnnounce_.add(input.readMessage(Powerbrokermsg.AuctionAnnounceMessage.parser(), extensionRegistry));
              break;
            }
            case 26: {
              Powerbrokermsg.AuctionBeginMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = auctionBegin_.toBuilder();
              }
              auctionBegin_ = input.readMessage(Powerbrokermsg.AuctionBeginMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(auctionBegin_);
                auctionBegin_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              auctionData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          auctionAnnounce_ = java.util.Collections.unmodifiableList(auctionAnnounce_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_BaseMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_BaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Powerbrokermsg.BaseMessage.class, Powerbrokermsg.BaseMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code com.cyberpointllc.stac.powerbroker.BaseMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CONNECTION_START = 1;</code>
       */
      CONNECTION_START(0, 1),
      /**
       * <code>AUCTION_ANNOUNCE = 2;</code>
       */
      AUCTION_ANNOUNCE(1, 2),
      /**
       * <code>AUCTION_BEGIN = 3;</code>
       */
      AUCTION_BEGIN(2, 3),
      /**
       * <code>BIDDING_FINISHED = 4;</code>
       */
      BIDDING_FINISHED(3, 4),
      /**
       * <code>AUCTION_DATA = 5;</code>
       *
       * <pre>
       * contains data used by the underlying auction API
       * </pre>
       */
      AUCTION_DATA(4, 5),
      /**
       * <code>AUCTION_END = 6;</code>
       */
      AUCTION_END(5, 6),
      /**
       * <code>RESULTS_END = 7;</code>
       */
      RESULTS_END(6, 7),
      /**
       * <code>PROCESS_START = 8;</code>
       */
      PROCESS_START(7, 8),
      ;

      /**
       * <code>CONNECTION_START = 1;</code>
       */
      public static final int CONNECTION_START_VALUE = 1;
      /**
       * <code>AUCTION_ANNOUNCE = 2;</code>
       */
      public static final int AUCTION_ANNOUNCE_VALUE = 2;
      /**
       * <code>AUCTION_BEGIN = 3;</code>
       */
      public static final int AUCTION_BEGIN_VALUE = 3;
      /**
       * <code>BIDDING_FINISHED = 4;</code>
       */
      public static final int BIDDING_FINISHED_VALUE = 4;
      /**
       * <code>AUCTION_DATA = 5;</code>
       *
       * <pre>
       * contains data used by the underlying auction API
       * </pre>
       */
      public static final int AUCTION_DATA_VALUE = 5;
      /**
       * <code>AUCTION_END = 6;</code>
       */
      public static final int AUCTION_END_VALUE = 6;
      /**
       * <code>RESULTS_END = 7;</code>
       */
      public static final int RESULTS_END_VALUE = 7;
      /**
       * <code>PROCESS_START = 8;</code>
       */
      public static final int PROCESS_START_VALUE = 8;


      public final int getNumber() {
        return value;
      }

      public static Type valueOf(int value) {
        switch (value) {
          case 1: return CONNECTION_START;
          case 2: return AUCTION_ANNOUNCE;
          case 3: return AUCTION_BEGIN;
          case 4: return BIDDING_FINISHED;
          case 5: return AUCTION_DATA;
          case 6: return AUCTION_END;
          case 7: return RESULTS_END;
          case 8: return PROCESS_START;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Powerbrokermsg.BaseMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.cyberpointllc.stac.powerbroker.BaseMessage.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required .com.cyberpointllc.stac.powerbroker.BaseMessage.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.cyberpointllc.stac.powerbroker.BaseMessage.Type type = 1;</code>
     */
    public Powerbrokermsg.BaseMessage.Type getType() {
      Powerbrokermsg.BaseMessage.Type result = Powerbrokermsg.BaseMessage.Type.valueOf(type_);
      return result == null ? Powerbrokermsg.BaseMessage.Type.CONNECTION_START : result;
    }

    public static final int AUCTIONANNOUNCE_FIELD_NUMBER = 2;
    private java.util.List<Powerbrokermsg.AuctionAnnounceMessage> auctionAnnounce_;
    /**
     * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
     *
     * <pre>
     * we announce all of the auctions we're holding at the same time
     * </pre>
     */
    public java.util.List<Powerbrokermsg.AuctionAnnounceMessage> getAuctionAnnounceList() {
      return auctionAnnounce_;
    }
    /**
     * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
     *
     * <pre>
     * we announce all of the auctions we're holding at the same time
     * </pre>
     */
    public java.util.List<? extends Powerbrokermsg.AuctionAnnounceMessageOrBuilder>
        getAuctionAnnounceOrBuilderList() {
      return auctionAnnounce_;
    }
    /**
     * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
     *
     * <pre>
     * we announce all of the auctions we're holding at the same time
     * </pre>
     */
    public int getAuctionAnnounceCount() {
      return auctionAnnounce_.size();
    }
    /**
     * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
     *
     * <pre>
     * we announce all of the auctions we're holding at the same time
     * </pre>
     */
    public Powerbrokermsg.AuctionAnnounceMessage getAuctionAnnounce(int index) {
      return auctionAnnounce_.get(index);
    }
    /**
     * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
     *
     * <pre>
     * we announce all of the auctions we're holding at the same time
     * </pre>
     */
    public Powerbrokermsg.AuctionAnnounceMessageOrBuilder getAuctionAnnounceOrBuilder(
        int index) {
      return auctionAnnounce_.get(index);
    }

    public static final int AUCTIONBEGIN_FIELD_NUMBER = 3;
    private Powerbrokermsg.AuctionBeginMessage auctionBegin_;
    /**
     * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
     *
     * <pre>
     * you're only allowed to start one auction at a time
     * </pre>
     */
    public boolean hasAuctionBegin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
     *
     * <pre>
     * you're only allowed to start one auction at a time
     * </pre>
     */
    public Powerbrokermsg.AuctionBeginMessage getAuctionBegin() {
      return auctionBegin_ == null ? Powerbrokermsg.AuctionBeginMessage.getDefaultInstance() : auctionBegin_;
    }
    /**
     * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
     *
     * <pre>
     * you're only allowed to start one auction at a time
     * </pre>
     */
    public Powerbrokermsg.AuctionBeginMessageOrBuilder getAuctionBeginOrBuilder() {
      return auctionBegin_ == null ? Powerbrokermsg.AuctionBeginMessage.getDefaultInstance() : auctionBegin_;
    }

    public static final int AUCTIONDATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString auctionData_;
    /**
     * <code>optional bytes auctionData = 4;</code>
     *
     * <pre>
     * the bytes for auction api messageds
     * </pre>
     */
    public boolean hasAuctionData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes auctionData = 4;</code>
     *
     * <pre>
     * the bytes for auction api messageds
     * </pre>
     */
    public com.google.protobuf.ByteString getAuctionData() {
      return auctionData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAuctionAnnounceCount(); i++) {
        if (!getAuctionAnnounce(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasAuctionBegin()) {
        if (!getAuctionBegin().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      for (int i = 0; i < auctionAnnounce_.size(); i++) {
        output.writeMessage(2, auctionAnnounce_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, getAuctionBegin());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, auctionData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      for (int i = 0; i < auctionAnnounce_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, auctionAnnounce_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getAuctionBegin());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, auctionData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Powerbrokermsg.BaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Powerbrokermsg.BaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Powerbrokermsg.BaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Powerbrokermsg.BaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Powerbrokermsg.BaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Powerbrokermsg.BaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Powerbrokermsg.BaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Powerbrokermsg.BaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Powerbrokermsg.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Powerbrokermsg.BaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Powerbrokermsg.BaseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cyberpointllc.stac.powerbroker.BaseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cyberpointllc.stac.powerbroker.BaseMessage)
        Powerbrokermsg.BaseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_BaseMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_BaseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Powerbrokermsg.BaseMessage.class, Powerbrokermsg.BaseMessage.Builder.class);
      }

      // Construct using com.cyberpointllc.stac.powerbroker.Powerbrokermsg.BaseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAuctionAnnounceFieldBuilder();
          getAuctionBeginFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (auctionAnnounceBuilder_ == null) {
          auctionAnnounce_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          auctionAnnounceBuilder_.clear();
        }
        if (auctionBeginBuilder_ == null) {
          auctionBegin_ = null;
        } else {
          auctionBeginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        auctionData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_BaseMessage_descriptor;
      }

      public Powerbrokermsg.BaseMessage getDefaultInstanceForType() {
        return Powerbrokermsg.BaseMessage.getDefaultInstance();
      }

      public Powerbrokermsg.BaseMessage build() {
        Powerbrokermsg.BaseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public Powerbrokermsg.BaseMessage buildPartial() {
        Powerbrokermsg.BaseMessage result = new Powerbrokermsg.BaseMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (auctionAnnounceBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            auctionAnnounce_ = java.util.Collections.unmodifiableList(auctionAnnounce_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.auctionAnnounce_ = auctionAnnounce_;
        } else {
          result.auctionAnnounce_ = auctionAnnounceBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (auctionBeginBuilder_ == null) {
          result.auctionBegin_ = auctionBegin_;
        } else {
          result.auctionBegin_ = auctionBeginBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.auctionData_ = auctionData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Powerbrokermsg.BaseMessage) {
          return mergeFrom((Powerbrokermsg.BaseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Powerbrokermsg.BaseMessage other) {
        if (other == Powerbrokermsg.BaseMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (auctionAnnounceBuilder_ == null) {
          if (!other.auctionAnnounce_.isEmpty()) {
            if (auctionAnnounce_.isEmpty()) {
              auctionAnnounce_ = other.auctionAnnounce_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAuctionAnnounceIsMutable();
              auctionAnnounce_.addAll(other.auctionAnnounce_);
            }
            onChanged();
          }
        } else {
          if (!other.auctionAnnounce_.isEmpty()) {
            if (auctionAnnounceBuilder_.isEmpty()) {
              auctionAnnounceBuilder_.dispose();
              auctionAnnounceBuilder_ = null;
              auctionAnnounce_ = other.auctionAnnounce_;
              bitField0_ = (bitField0_ & ~0x00000002);
              auctionAnnounceBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAuctionAnnounceFieldBuilder() : null;
            } else {
              auctionAnnounceBuilder_.addAllMessages(other.auctionAnnounce_);
            }
          }
        }
        if (other.hasAuctionBegin()) {
          mergeAuctionBegin(other.getAuctionBegin());
        }
        if (other.hasAuctionData()) {
          setAuctionData(other.getAuctionData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        for (int i = 0; i < getAuctionAnnounceCount(); i++) {
          if (!getAuctionAnnounce(i).isInitialized()) {
            return false;
          }
        }
        if (hasAuctionBegin()) {
          if (!getAuctionBegin().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Powerbrokermsg.BaseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Powerbrokermsg.BaseMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 1;
      /**
       * <code>required .com.cyberpointllc.stac.powerbroker.BaseMessage.Type type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.cyberpointllc.stac.powerbroker.BaseMessage.Type type = 1;</code>
       */
      public Powerbrokermsg.BaseMessage.Type getType() {
        Powerbrokermsg.BaseMessage.Type result = Powerbrokermsg.BaseMessage.Type.valueOf(type_);
        return result == null ? Powerbrokermsg.BaseMessage.Type.CONNECTION_START : result;
      }
      /**
       * <code>required .com.cyberpointllc.stac.powerbroker.BaseMessage.Type type = 1;</code>
       */
      public Builder setType(Powerbrokermsg.BaseMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .com.cyberpointllc.stac.powerbroker.BaseMessage.Type type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }

      private java.util.List<Powerbrokermsg.AuctionAnnounceMessage> auctionAnnounce_ =
        java.util.Collections.emptyList();
      private void ensureAuctionAnnounceIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          auctionAnnounce_ = new java.util.ArrayList<Powerbrokermsg.AuctionAnnounceMessage>(auctionAnnounce_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Powerbrokermsg.AuctionAnnounceMessage, Powerbrokermsg.AuctionAnnounceMessage.Builder, Powerbrokermsg.AuctionAnnounceMessageOrBuilder> auctionAnnounceBuilder_;

      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public java.util.List<Powerbrokermsg.AuctionAnnounceMessage> getAuctionAnnounceList() {
        if (auctionAnnounceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(auctionAnnounce_);
        } else {
          return auctionAnnounceBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public int getAuctionAnnounceCount() {
        if (auctionAnnounceBuilder_ == null) {
          return auctionAnnounce_.size();
        } else {
          return auctionAnnounceBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Powerbrokermsg.AuctionAnnounceMessage getAuctionAnnounce(int index) {
        if (auctionAnnounceBuilder_ == null) {
          return auctionAnnounce_.get(index);
        } else {
          return auctionAnnounceBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Builder setAuctionAnnounce(
          int index, Powerbrokermsg.AuctionAnnounceMessage value) {
        if (auctionAnnounceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuctionAnnounceIsMutable();
          auctionAnnounce_.set(index, value);
          onChanged();
        } else {
          auctionAnnounceBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Builder setAuctionAnnounce(
          int index, Powerbrokermsg.AuctionAnnounceMessage.Builder builderForValue) {
        if (auctionAnnounceBuilder_ == null) {
          ensureAuctionAnnounceIsMutable();
          auctionAnnounce_.set(index, builderForValue.build());
          onChanged();
        } else {
          auctionAnnounceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Builder addAuctionAnnounce(Powerbrokermsg.AuctionAnnounceMessage value) {
        if (auctionAnnounceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuctionAnnounceIsMutable();
          auctionAnnounce_.add(value);
          onChanged();
        } else {
          auctionAnnounceBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Builder addAuctionAnnounce(
          int index, Powerbrokermsg.AuctionAnnounceMessage value) {
        if (auctionAnnounceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAuctionAnnounceIsMutable();
          auctionAnnounce_.add(index, value);
          onChanged();
        } else {
          auctionAnnounceBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Builder addAuctionAnnounce(
          Powerbrokermsg.AuctionAnnounceMessage.Builder builderForValue) {
        if (auctionAnnounceBuilder_ == null) {
          ensureAuctionAnnounceIsMutable();
          auctionAnnounce_.add(builderForValue.build());
          onChanged();
        } else {
          auctionAnnounceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Builder addAuctionAnnounce(
          int index, Powerbrokermsg.AuctionAnnounceMessage.Builder builderForValue) {
        if (auctionAnnounceBuilder_ == null) {
          ensureAuctionAnnounceIsMutable();
          auctionAnnounce_.add(index, builderForValue.build());
          onChanged();
        } else {
          auctionAnnounceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Builder addAllAuctionAnnounce(
          java.lang.Iterable<? extends Powerbrokermsg.AuctionAnnounceMessage> values) {
        if (auctionAnnounceBuilder_ == null) {
          ensureAuctionAnnounceIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, auctionAnnounce_);
          onChanged();
        } else {
          auctionAnnounceBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Builder clearAuctionAnnounce() {
        if (auctionAnnounceBuilder_ == null) {
          auctionAnnounce_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          auctionAnnounceBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Builder removeAuctionAnnounce(int index) {
        if (auctionAnnounceBuilder_ == null) {
          ensureAuctionAnnounceIsMutable();
          auctionAnnounce_.remove(index);
          onChanged();
        } else {
          auctionAnnounceBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Powerbrokermsg.AuctionAnnounceMessage.Builder getAuctionAnnounceBuilder(
          int index) {
        return getAuctionAnnounceFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Powerbrokermsg.AuctionAnnounceMessageOrBuilder getAuctionAnnounceOrBuilder(
          int index) {
        if (auctionAnnounceBuilder_ == null) {
          return auctionAnnounce_.get(index);  } else {
          return auctionAnnounceBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public java.util.List<? extends Powerbrokermsg.AuctionAnnounceMessageOrBuilder>
           getAuctionAnnounceOrBuilderList() {
        if (auctionAnnounceBuilder_ != null) {
          return auctionAnnounceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(auctionAnnounce_);
        }
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Powerbrokermsg.AuctionAnnounceMessage.Builder addAuctionAnnounceBuilder() {
        return getAuctionAnnounceFieldBuilder().addBuilder(
            Powerbrokermsg.AuctionAnnounceMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public Powerbrokermsg.AuctionAnnounceMessage.Builder addAuctionAnnounceBuilder(
          int index) {
        return getAuctionAnnounceFieldBuilder().addBuilder(
            index, Powerbrokermsg.AuctionAnnounceMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage auctionAnnounce = 2;</code>
       *
       * <pre>
       * we announce all of the auctions we're holding at the same time
       * </pre>
       */
      public java.util.List<Powerbrokermsg.AuctionAnnounceMessage.Builder>
           getAuctionAnnounceBuilderList() {
        return getAuctionAnnounceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Powerbrokermsg.AuctionAnnounceMessage, Powerbrokermsg.AuctionAnnounceMessage.Builder, Powerbrokermsg.AuctionAnnounceMessageOrBuilder>
          getAuctionAnnounceFieldBuilder() {
        if (auctionAnnounceBuilder_ == null) {
          auctionAnnounceBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Powerbrokermsg.AuctionAnnounceMessage, Powerbrokermsg.AuctionAnnounceMessage.Builder, Powerbrokermsg.AuctionAnnounceMessageOrBuilder>(
                  auctionAnnounce_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          auctionAnnounce_ = null;
        }
        return auctionAnnounceBuilder_;
      }

      private Powerbrokermsg.AuctionBeginMessage auctionBegin_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          Powerbrokermsg.AuctionBeginMessage, Powerbrokermsg.AuctionBeginMessage.Builder, Powerbrokermsg.AuctionBeginMessageOrBuilder> auctionBeginBuilder_;
      /**
       * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
       *
       * <pre>
       * you're only allowed to start one auction at a time
       * </pre>
       */
      public boolean hasAuctionBegin() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
       *
       * <pre>
       * you're only allowed to start one auction at a time
       * </pre>
       */
      public Powerbrokermsg.AuctionBeginMessage getAuctionBegin() {
        if (auctionBeginBuilder_ == null) {
          return auctionBegin_ == null ? Powerbrokermsg.AuctionBeginMessage.getDefaultInstance() : auctionBegin_;
        } else {
          return auctionBeginBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
       *
       * <pre>
       * you're only allowed to start one auction at a time
       * </pre>
       */
      public Builder setAuctionBegin(Powerbrokermsg.AuctionBeginMessage value) {
        if (auctionBeginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          auctionBegin_ = value;
          onChanged();
        } else {
          auctionBeginBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
       *
       * <pre>
       * you're only allowed to start one auction at a time
       * </pre>
       */
      public Builder setAuctionBegin(
          Powerbrokermsg.AuctionBeginMessage.Builder builderForValue) {
        if (auctionBeginBuilder_ == null) {
          auctionBegin_ = builderForValue.build();
          onChanged();
        } else {
          auctionBeginBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
       *
       * <pre>
       * you're only allowed to start one auction at a time
       * </pre>
       */
      public Builder mergeAuctionBegin(Powerbrokermsg.AuctionBeginMessage value) {
        if (auctionBeginBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              auctionBegin_ != null &&
              auctionBegin_ != Powerbrokermsg.AuctionBeginMessage.getDefaultInstance()) {
            auctionBegin_ =
              Powerbrokermsg.AuctionBeginMessage.newBuilder(auctionBegin_).mergeFrom(value).buildPartial();
          } else {
            auctionBegin_ = value;
          }
          onChanged();
        } else {
          auctionBeginBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
       *
       * <pre>
       * you're only allowed to start one auction at a time
       * </pre>
       */
      public Builder clearAuctionBegin() {
        if (auctionBeginBuilder_ == null) {
          auctionBegin_ = null;
          onChanged();
        } else {
          auctionBeginBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
       *
       * <pre>
       * you're only allowed to start one auction at a time
       * </pre>
       */
      public Powerbrokermsg.AuctionBeginMessage.Builder getAuctionBeginBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getAuctionBeginFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
       *
       * <pre>
       * you're only allowed to start one auction at a time
       * </pre>
       */
      public Powerbrokermsg.AuctionBeginMessageOrBuilder getAuctionBeginOrBuilder() {
        if (auctionBeginBuilder_ != null) {
          return auctionBeginBuilder_.getMessageOrBuilder();
        } else {
          return auctionBegin_ == null ?
              Powerbrokermsg.AuctionBeginMessage.getDefaultInstance() : auctionBegin_;
        }
      }
      /**
       * <code>optional .com.cyberpointllc.stac.powerbroker.AuctionBeginMessage auctionBegin = 3;</code>
       *
       * <pre>
       * you're only allowed to start one auction at a time
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          Powerbrokermsg.AuctionBeginMessage, Powerbrokermsg.AuctionBeginMessage.Builder, Powerbrokermsg.AuctionBeginMessageOrBuilder>
          getAuctionBeginFieldBuilder() {
        if (auctionBeginBuilder_ == null) {
          auctionBeginBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Powerbrokermsg.AuctionBeginMessage, Powerbrokermsg.AuctionBeginMessage.Builder, Powerbrokermsg.AuctionBeginMessageOrBuilder>(
                  getAuctionBegin(),
                  getParentForChildren(),
                  isClean());
          auctionBegin_ = null;
        }
        return auctionBeginBuilder_;
      }

      private com.google.protobuf.ByteString auctionData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes auctionData = 4;</code>
       *
       * <pre>
       * the bytes for auction api messageds
       * </pre>
       */
      public boolean hasAuctionData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes auctionData = 4;</code>
       *
       * <pre>
       * the bytes for auction api messageds
       * </pre>
       */
      public com.google.protobuf.ByteString getAuctionData() {
        return auctionData_;
      }
      /**
       * <code>optional bytes auctionData = 4;</code>
       *
       * <pre>
       * the bytes for auction api messageds
       * </pre>
       */
      public Builder setAuctionData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        auctionData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes auctionData = 4;</code>
       *
       * <pre>
       * the bytes for auction api messageds
       * </pre>
       */
      public Builder clearAuctionData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        auctionData_ = getDefaultInstance().getAuctionData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.cyberpointllc.stac.powerbroker.BaseMessage)
    }

    // @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.powerbroker.BaseMessage)
    private static final Powerbrokermsg.BaseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Powerbrokermsg.BaseMessage();
    }

    public static Powerbrokermsg.BaseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<BaseMessage>
        PARSER = new com.google.protobuf.AbstractParser<BaseMessage>() {
      public BaseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new BaseMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<BaseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseMessage> getParserForType() {
      return PARSER;
    }

    public Powerbrokermsg.BaseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuctionAnnounceMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 powerAmount = 1;</code>
     */
    boolean hasPowerAmount();
    /**
     * <code>required uint32 powerAmount = 1;</code>
     */
    int getPowerAmount();

    /**
     * <code>required string id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 2;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 2;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage}
   */
  public  static final class AuctionAnnounceMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage)
      AuctionAnnounceMessageOrBuilder {
    // Use AuctionAnnounceMessage.newBuilder() to construct.
    private AuctionAnnounceMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AuctionAnnounceMessage() {
      powerAmount_ = 0;
      id_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuctionAnnounceMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              powerAmount_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              id_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_AuctionAnnounceMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_AuctionAnnounceMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Powerbrokermsg.AuctionAnnounceMessage.class, Powerbrokermsg.AuctionAnnounceMessage.Builder.class);
    }

    private int bitField0_;
    public static final int POWERAMOUNT_FIELD_NUMBER = 1;
    private int powerAmount_;
    /**
     * <code>required uint32 powerAmount = 1;</code>
     */
    public boolean hasPowerAmount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 powerAmount = 1;</code>
     */
    public int getPowerAmount() {
      return powerAmount_;
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPowerAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, powerAmount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, id_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, powerAmount_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Powerbrokermsg.AuctionAnnounceMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Powerbrokermsg.AuctionAnnounceMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Powerbrokermsg.AuctionAnnounceMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Powerbrokermsg.AuctionAnnounceMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Powerbrokermsg.AuctionAnnounceMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Powerbrokermsg.AuctionAnnounceMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Powerbrokermsg.AuctionAnnounceMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Powerbrokermsg.AuctionAnnounceMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Powerbrokermsg.AuctionAnnounceMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Powerbrokermsg.AuctionAnnounceMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Powerbrokermsg.AuctionAnnounceMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage)
        Powerbrokermsg.AuctionAnnounceMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_AuctionAnnounceMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_AuctionAnnounceMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Powerbrokermsg.AuctionAnnounceMessage.class, Powerbrokermsg.AuctionAnnounceMessage.Builder.class);
      }

      // Construct using com.cyberpointllc.stac.powerbroker.Powerbrokermsg.AuctionAnnounceMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        powerAmount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_AuctionAnnounceMessage_descriptor;
      }

      public Powerbrokermsg.AuctionAnnounceMessage getDefaultInstanceForType() {
        return Powerbrokermsg.AuctionAnnounceMessage.getDefaultInstance();
      }

      public Powerbrokermsg.AuctionAnnounceMessage build() {
        Powerbrokermsg.AuctionAnnounceMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public Powerbrokermsg.AuctionAnnounceMessage buildPartial() {
        Powerbrokermsg.AuctionAnnounceMessage result = new Powerbrokermsg.AuctionAnnounceMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.powerAmount_ = powerAmount_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Powerbrokermsg.AuctionAnnounceMessage) {
          return mergeFrom((Powerbrokermsg.AuctionAnnounceMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Powerbrokermsg.AuctionAnnounceMessage other) {
        if (other == Powerbrokermsg.AuctionAnnounceMessage.getDefaultInstance()) return this;
        if (other.hasPowerAmount()) {
          setPowerAmount(other.getPowerAmount());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000002;
          id_ = other.id_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPowerAmount()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Powerbrokermsg.AuctionAnnounceMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Powerbrokermsg.AuctionAnnounceMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int powerAmount_ ;
      /**
       * <code>required uint32 powerAmount = 1;</code>
       */
      public boolean hasPowerAmount() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 powerAmount = 1;</code>
       */
      public int getPowerAmount() {
        return powerAmount_;
      }
      /**
       * <code>required uint32 powerAmount = 1;</code>
       */
      public Builder setPowerAmount(int value) {
        bitField0_ |= 0x00000001;
        powerAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 powerAmount = 1;</code>
       */
      public Builder clearPowerAmount() {
        bitField0_ = (bitField0_ & ~0x00000001);
        powerAmount_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string id = 2;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 2;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 2;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage)
    }

    // @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.powerbroker.AuctionAnnounceMessage)
    private static final Powerbrokermsg.AuctionAnnounceMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Powerbrokermsg.AuctionAnnounceMessage();
    }

    public static Powerbrokermsg.AuctionAnnounceMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AuctionAnnounceMessage>
        PARSER = new com.google.protobuf.AbstractParser<AuctionAnnounceMessage>() {
      public AuctionAnnounceMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new AuctionAnnounceMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<AuctionAnnounceMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuctionAnnounceMessage> getParserForType() {
      return PARSER;
    }

    public Powerbrokermsg.AuctionAnnounceMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AuctionBeginMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.cyberpointllc.stac.powerbroker.AuctionBeginMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string auctionId = 1;</code>
     */
    boolean hasAuctionId();
    /**
     * <code>required string auctionId = 1;</code>
     */
    java.lang.String getAuctionId();
    /**
     * <code>required string auctionId = 1;</code>
     */
    com.google.protobuf.ByteString
        getAuctionIdBytes();

    /**
     * <code>required uint32 powerAmount = 2;</code>
     */
    boolean hasPowerAmount();
    /**
     * <code>required uint32 powerAmount = 2;</code>
     */
    int getPowerAmount();
  }
  /**
   * Protobuf type {@code com.cyberpointllc.stac.powerbroker.AuctionBeginMessage}
   */
  public  static final class AuctionBeginMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.cyberpointllc.stac.powerbroker.AuctionBeginMessage)
      AuctionBeginMessageOrBuilder {
    // Use AuctionBeginMessage.newBuilder() to construct.
    private AuctionBeginMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AuctionBeginMessage() {
      auctionId_ = "";
      powerAmount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AuctionBeginMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              auctionId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              powerAmount_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_AuctionBeginMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_AuctionBeginMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Powerbrokermsg.AuctionBeginMessage.class, Powerbrokermsg.AuctionBeginMessage.Builder.class);
    }

    private int bitField0_;
    public static final int AUCTIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object auctionId_;
    /**
     * <code>required string auctionId = 1;</code>
     */
    public boolean hasAuctionId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string auctionId = 1;</code>
     */
    public java.lang.String getAuctionId() {
      java.lang.Object ref = auctionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          auctionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string auctionId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAuctionIdBytes() {
      java.lang.Object ref = auctionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        auctionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POWERAMOUNT_FIELD_NUMBER = 2;
    private int powerAmount_;
    /**
     * <code>required uint32 powerAmount = 2;</code>
     */
    public boolean hasPowerAmount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 powerAmount = 2;</code>
     */
    public int getPowerAmount() {
      return powerAmount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasAuctionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPowerAmount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, auctionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, powerAmount_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, auctionId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, powerAmount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static Powerbrokermsg.AuctionBeginMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Powerbrokermsg.AuctionBeginMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Powerbrokermsg.AuctionBeginMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Powerbrokermsg.AuctionBeginMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Powerbrokermsg.AuctionBeginMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Powerbrokermsg.AuctionBeginMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Powerbrokermsg.AuctionBeginMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Powerbrokermsg.AuctionBeginMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Powerbrokermsg.AuctionBeginMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Powerbrokermsg.AuctionBeginMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Powerbrokermsg.AuctionBeginMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.cyberpointllc.stac.powerbroker.AuctionBeginMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.cyberpointllc.stac.powerbroker.AuctionBeginMessage)
        Powerbrokermsg.AuctionBeginMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_AuctionBeginMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_AuctionBeginMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Powerbrokermsg.AuctionBeginMessage.class, Powerbrokermsg.AuctionBeginMessage.Builder.class);
      }

      // Construct using com.cyberpointllc.stac.powerbroker.Powerbrokermsg.AuctionBeginMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        auctionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        powerAmount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Powerbrokermsg.internal_static_com_cyberpointllc_stac_powerbroker_AuctionBeginMessage_descriptor;
      }

      public Powerbrokermsg.AuctionBeginMessage getDefaultInstanceForType() {
        return Powerbrokermsg.AuctionBeginMessage.getDefaultInstance();
      }

      public Powerbrokermsg.AuctionBeginMessage build() {
        Powerbrokermsg.AuctionBeginMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }

      public Powerbrokermsg.AuctionBeginMessage buildPartial() {
        Powerbrokermsg.AuctionBeginMessage result = new Powerbrokermsg.AuctionBeginMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.auctionId_ = auctionId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.powerAmount_ = powerAmount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Powerbrokermsg.AuctionBeginMessage) {
          return mergeFrom((Powerbrokermsg.AuctionBeginMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Powerbrokermsg.AuctionBeginMessage other) {
        if (other == Powerbrokermsg.AuctionBeginMessage.getDefaultInstance()) return this;
        if (other.hasAuctionId()) {
          bitField0_ |= 0x00000001;
          auctionId_ = other.auctionId_;
          onChanged();
        }
        if (other.hasPowerAmount()) {
          setPowerAmount(other.getPowerAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAuctionId()) {
          return false;
        }
        if (!hasPowerAmount()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Powerbrokermsg.AuctionBeginMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Powerbrokermsg.AuctionBeginMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object auctionId_ = "";
      /**
       * <code>required string auctionId = 1;</code>
       */
      public boolean hasAuctionId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string auctionId = 1;</code>
       */
      public java.lang.String getAuctionId() {
        java.lang.Object ref = auctionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            auctionId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string auctionId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAuctionIdBytes() {
        java.lang.Object ref = auctionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          auctionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string auctionId = 1;</code>
       */
      public Builder setAuctionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        auctionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string auctionId = 1;</code>
       */
      public Builder clearAuctionId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        auctionId_ = getDefaultInstance().getAuctionId();
        onChanged();
        return this;
      }
      /**
       * <code>required string auctionId = 1;</code>
       */
      public Builder setAuctionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        auctionId_ = value;
        onChanged();
        return this;
      }

      private int powerAmount_ ;
      /**
       * <code>required uint32 powerAmount = 2;</code>
       */
      public boolean hasPowerAmount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 powerAmount = 2;</code>
       */
      public int getPowerAmount() {
        return powerAmount_;
      }
      /**
       * <code>required uint32 powerAmount = 2;</code>
       */
      public Builder setPowerAmount(int value) {
        bitField0_ |= 0x00000002;
        powerAmount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 powerAmount = 2;</code>
       */
      public Builder clearPowerAmount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        powerAmount_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.cyberpointllc.stac.powerbroker.AuctionBeginMessage)
    }

    // @@protoc_insertion_point(class_scope:com.cyberpointllc.stac.powerbroker.AuctionBeginMessage)
    private static final Powerbrokermsg.AuctionBeginMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Powerbrokermsg.AuctionBeginMessage();
    }

    public static Powerbrokermsg.AuctionBeginMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<AuctionBeginMessage>
        PARSER = new com.google.protobuf.AbstractParser<AuctionBeginMessage>() {
      public AuctionBeginMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new AuctionBeginMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<AuctionBeginMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AuctionBeginMessage> getParserForType() {
      return PARSER;
    }

    public Powerbrokermsg.AuctionBeginMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cyberpointllc_stac_powerbroker_BaseMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cyberpointllc_stac_powerbroker_BaseMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cyberpointllc_stac_powerbroker_AuctionAnnounceMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cyberpointllc_stac_powerbroker_AuctionAnnounceMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_cyberpointllc_stac_powerbroker_AuctionBeginMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_cyberpointllc_stac_powerbroker_AuctionBeginMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024powerbrokermsg.proto\022\"com.cyberpointll" +
      "c.stac.powerbroker\"\257\003\n\013BaseMessage\022B\n\004ty" +
      "pe\030\001 \002(\01624.com.cyberpointllc.stac.powerb" +
      "roker.BaseMessage.Type\022S\n\017auctionAnnounc" +
      "e\030\002 \003(\0132:.com.cyberpointllc.stac.powerbr" +
      "oker.AuctionAnnounceMessage\022M\n\014auctionBe" +
      "gin\030\003 \001(\01327.com.cyberpointllc.stac.power" +
      "broker.AuctionBeginMessage\022\023\n\013auctionDat" +
      "a\030\004 \001(\014\"\242\001\n\004Type\022\024\n\020CONNECTION_START\020\001\022\024" +
      "\n\020AUCTION_ANNOUNCE\020\002\022\021\n\rAUCTION_BEGIN\020\003\022",
      "\024\n\020BIDDING_FINISHED\020\004\022\020\n\014AUCTION_DATA\020\005\022" +
      "\017\n\013AUCTION_END\020\006\022\017\n\013RESULTS_END\020\007\022\021\n\rPRO" +
      "CESS_START\020\010\"9\n\026AuctionAnnounceMessage\022\023" +
      "\n\013powerAmount\030\001 \002(\r\022\n\n\002id\030\002 \002(\t\"=\n\023Aucti" +
      "onBeginMessage\022\021\n\tauctionId\030\001 \002(\t\022\023\n\013pow" +
      "erAmount\030\002 \002(\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_cyberpointllc_stac_powerbroker_BaseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_cyberpointllc_stac_powerbroker_BaseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_cyberpointllc_stac_powerbroker_BaseMessage_descriptor,
        new java.lang.String[] { "Type", "AuctionAnnounce", "AuctionBegin", "AuctionData", });
    internal_static_com_cyberpointllc_stac_powerbroker_AuctionAnnounceMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_cyberpointllc_stac_powerbroker_AuctionAnnounceMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_cyberpointllc_stac_powerbroker_AuctionAnnounceMessage_descriptor,
        new java.lang.String[] { "PowerAmount", "Id", });
    internal_static_com_cyberpointllc_stac_powerbroker_AuctionBeginMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_cyberpointllc_stac_powerbroker_AuctionBeginMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_cyberpointllc_stac_powerbroker_AuctionBeginMessage_descriptor,
        new java.lang.String[] { "AuctionId", "PowerAmount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
